#################### Dataset ####################
# Dataset Index: 1, 2
dataset_index: 2

#################### Model ####################

# Available Models: ResNet34, ResNet50, DesNet, ResNeXt50, ConvNeXt_Tiny, ConvNeXt_Small, ConvNeXt_Base, ConvNeXt_Large
model_name: ConvNeXt_Base
# Adapatation: True, False
adaptation: True
adaptation_pretrained: True
cnn_pretrained: False
view_adaptated_image: False


#################### Training ####################
test: False
# Training Parameters
batch_size: 32
num_epochs: 6
learning_rate: 0.002
# Optimizer: Adam, SGD
optimizer: SGD
# Training Round: Reset the CNN and retain the adaptation network after each round
training_round: 10